// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "aiWrite": {
    "editor": {
      "initialContent": "# Hello World"
    },
    "header": {
      "back": "Back"
    }
  },
  "auth": {
    "brand": {
      "name": "Knowledge Base"
    },
    "form": {
      "email": {
        "invalid": "Please enter a valid email address",
        "label": "Email",
        "max": "Email must be no longer than 100 characters",
        "placeholder": "Enter your email"
      },
      "password": {
        "label": "Password",
        "placeholder": "Enter your password",
        "range": "Password must be between 8 and 32 characters"
      },
      "username": {
        "label": "Username",
        "placeholder": "Enter your username",
        "range": "Username must be between 2 and 30 characters"
      }
    },
    "login": {
      "button": "Log in",
      "description": "Enter your email and password to continue to the knowledge workspace.",
      "footerLinkText": "Sign up now",
      "footerText": "Don't have an account yet?",
      "imageAlt": "Interactive illustration for the login page",
      "title": "Log in to your account"
    },
    "register": {
      "button": "Sign up",
      "description": "Fill in the details below to quickly create your knowledge workspace account.",
      "footerLinkText": "Go to log in",
      "footerText": "Already have an account?",
      "imageAlt": "Interactive illustration for the registration page",
      "title": "Create a new account"
    }
  },
  "chat": {
    "centeredComposer": {
      "general": {
        "description": "Ask directly, or create a knowledge-base conversation from the left before you start.",
        "title": "Start a new chat"
      },
      "knowledge": {
        "description": "This conversation will be linked to knowledge base \"{{name}}\". The session will only be created after you send the first message.",
        "title": "Start a knowledge-base chat"
      }
    },
    "defaults": {
      "generalConversation": "General conversation",
      "knowledgeConversation": "{{name}} conversation"
    },
    "errors": {
      "abort": "Stopped generating the answer",
      "failed": "This question failed. Please try again later",
      "retrievalTimeout": "Knowledge retrieval timed out. Please try again later",
      "selectConversation": "Please select a conversation first",
      "serviceUnavailable": "Knowledge service is temporarily unavailable. Please try again later"
    },
    "group": {
      "draft": "Pending start",
      "today": "Today",
      "yesterday": "Yesterday"
    },
    "knowledgeSelect": {
      "searchPlaceholder": "Search and select a knowledge base before creating a new conversation",
      "title": "New conversation",
      "withKnowledge": "Select a knowledge base to create a knowledge-base conversation",
      "withoutKnowledge": "Skip selection to create a general conversation"
    },
    "list": {
      "copy": "Copy",
      "sources": "Referenced {{count}} sources",
      "sourcesContentTitle": "Reference content",
      "sourcesTitle": "References",
      "thinking": "Generating an answer"
    },
    "placeholder": {
      "thinking": "Thinking..."
    },
    "reuse": {
      "general": "A general draft conversation already exists. Switched to it.",
      "knowledge": "A draft conversation for knowledge base \"{{name}}\" already exists. Switched to it."
    },
    "side": {
      "delete": {
        "content": "Deleting this conversation will also remove all of its message history. Continue?",
        "title": "Delete conversation"
      },
      "draftTag": "Pending",
      "home": "Home",
      "knowledgeTag": "Knowledge base",
      "menu": {
        "delete": "Delete conversation",
        "rename": "Rename"
      },
      "newConversation": "New conversation",
      "newConversationLabel": "Start a new conversation",
      "rename": {
        "placeholder": "Enter a new conversation title",
        "range": "Conversation title is required and must be no longer than 50 characters",
        "title": "Rename conversation"
      }
    }
  },
  "common": {
    "actions": {
      "back": "Back",
      "cancel": "Cancel",
      "confirm": "Confirm",
      "continue": "Continue",
      "create": "Create",
      "delete": "Delete",
      "download": "Download",
      "edit": "Edit",
      "logout": "Log out",
      "refresh": "Refresh",
      "save": "Save",
      "upload": "Upload",
      "viewAll": "View all",
      "viewDetails": "View details"
    },
    "labels": {
      "conversation": "Conversation",
      "description": "Description",
      "file": "File",
      "files": "Files",
      "home": "Home",
      "knowledgeBase": "Knowledge Base",
      "name": "Name"
    },
    "states": {
      "completed": "Completed",
      "loading": "Loading...",
      "pending": "Pending"
    }
  },
  "document": {
    "detail": {
      "description": "Document detail preview. You can view the content here and download the original file.",
      "downloadOriginal": "Download original file",
      "indexFailed": "Index failed",
      "notFound": "The document does not exist or failed to load",
      "unsupportedPreview": "Preview is not available for {{extension}} files"
    },
    "indexStatusMeta": {
      "completed": {
        "hint": "Indexing is complete. This document can be retrieved in searches.",
        "label": "Completed"
      },
      "failed": {
        "hint": "Indexing failed. This document will not appear in search results.",
        "label": "Failed"
      },
      "indexing": {
        "hint": "The document is being processed and may not be searchable yet.",
        "label": "Indexing"
      },
      "pending": {
        "hint": "The document is stored and waiting to be indexed.",
        "label": "Pending"
      }
    },
    "list": {
      "actions": "Actions",
      "bulkDelete": "Delete selected",
      "createdAt": "Created at",
      "deleteConfirm": "Are you sure you want to delete this document?",
      "extension": "Extension",
      "fileName": "File name",
      "fileSize": "File size",
      "fileType": "File type",
      "indexStatus": "Index status",
      "knowledgeBase": "Knowledge base",
      "refresh": "Refresh",
      "total": "Total {{count}} items",
      "updatedAt": "Updated at"
    },
    "preview": {
      "docxEmpty": "No DOCX content is available for preview",
      "docxFailed": "Failed to parse DOCX",
      "pdfEmpty": "No PDF content is available for preview",
      "pdfFailed": "Failed to load PDF",
      "pdfLoading": "Loading PDF...",
      "pdfNext": "Next page",
      "pdfPage": "Page {{current}}{{total}}",
      "pdfPrev": "Previous page"
    },
    "sourceType": {
      "editor": "Editor",
      "upload": "Upload"
    },
    "upload": {
      "button": "Upload files",
      "dragger": {
        "hint": "Only md, pdf, txt, and docx are supported. Each file must be smaller than 5 MB",
        "text": "Click or drag files to this area to upload"
      },
      "errors": {
        "fileTooLarge": "Each file must be smaller than 5 MB",
        "unsupportedFile": "Only md, pdf, txt, and docx files are supported"
      },
      "form": {
        "file": {
          "label": "File",
          "required": "Please upload at least one file"
        },
        "knowledgeBase": {
          "label": "Knowledge base",
          "required": "Please select a knowledge base"
        }
      },
      "helper": "Select a knowledge base and upload files",
      "modalTitle": "Upload files"
    }
  },
  "editor": {
    "admonitions": {
      "caution": "Caution",
      "changeType": "Select admonition type",
      "danger": "Danger",
      "info": "Info",
      "note": "Note",
      "placeholder": "Admonition type",
      "tip": "Tip"
    },
    "codeBlock": {
      "language": "Code block language",
      "selectLanguage": "Select code block language"
    },
    "codeBlockLanguages": {
      "unspecified": "Unspecified"
    },
    "contentArea": {
      "editableMarkdown": "Editable Markdown"
    },
    "createLink": {
      "cancelTooltip": "Cancel change",
      "saveTooltip": "Set URL",
      "text": "Anchor text",
      "textTooltip": "The text to display for the link",
      "title": "Link title",
      "titleTooltip": "The link title shown on hover",
      "url": "URL",
      "urlPlaceholder": "Select or paste a URL"
    },
    "dialogControls": {
      "cancel": "Cancel",
      "save": "Save"
    },
    "frontmatterEditor": {
      "addEntry": "Add entry",
      "key": "Key",
      "title": "Edit document frontmatter",
      "value": "Value"
    },
    "imageEditor": {
      "deleteImage": "Delete image",
      "editImage": "Edit image"
    },
    "linkPreview": {
      "copied": "Copied!",
      "copyToClipboard": "Copy to clipboard",
      "edit": "Edit link URL",
      "open": "Open {{url}} in a new window",
      "remove": "Remove link"
    },
    "table": {
      "alignCenter": "Align center",
      "alignLeft": "Align left",
      "alignRight": "Align right",
      "columnMenu": "Column menu",
      "deleteColumn": "Delete this column",
      "deleteRow": "Delete this row",
      "deleteTable": "Delete table",
      "insertColumnLeft": "Insert a column to the left",
      "insertColumnRight": "Insert a column to the right",
      "insertRowAbove": "Insert a row above",
      "insertRowBelow": "Insert a row below",
      "rowMenu": "Row menu",
      "textAlignment": "Text alignment"
    },
    "toolbar": {
      "admonition": "Insert admonition",
      "blockTypeSelect": {
        "placeholder": "Block type",
        "selectBlockTypeTooltip": "Select block type"
      },
      "blockTypes": {
        "heading": "Heading {{level}}",
        "paragraph": "Paragraph",
        "quote": "Quote"
      },
      "bold": "Bold",
      "bulletedList": "Bulleted list",
      "checkList": "Checklist",
      "codeBlock": "Insert code block",
      "deleteSandpack": "Delete this code block",
      "diffMode": "Diff mode",
      "editFrontmatter": "Edit frontmatter",
      "highlight": "Highlight",
      "image": "Insert image",
      "inlineCode": "Inline code",
      "insertFrontmatter": "Insert frontmatter",
      "insertSandpack": "Insert Sandpack",
      "italic": "Italic",
      "link": "Create link",
      "numberedList": "Numbered list",
      "redo": "Redo {{shortcut}}",
      "removeBold": "Remove bold",
      "removeHighlight": "Remove highlight",
      "removeInlineCode": "Remove inline code",
      "removeItalic": "Remove italic",
      "removeStrikethrough": "Remove strikethrough",
      "removeSubscript": "Remove subscript",
      "removeSuperscript": "Remove superscript",
      "removeUnderline": "Remove underline",
      "richText": "Rich text",
      "source": "Source mode",
      "strikethrough": "Strikethrough",
      "subscript": "Subscript",
      "superscript": "Superscript",
      "table": "Insert table",
      "thematicBreak": "Insert thematic break",
      "toggleGroup": "Toggle group",
      "underline": "Underline",
      "undo": "Undo {{shortcut}}"
    },
    "uploadImage": {
      "addViaUrlInstructions": "Or add an image from a URL:",
      "alt": "Alt:",
      "autoCompletePlaceholder": "Select or paste an image source",
      "dialogTitle": "Upload an image",
      "height": "Height:",
      "title": "Title:",
      "uploadInstructions": "Upload an image from your device:",
      "width": "Width:"
    }
  },
  "home": {
    "fallback": {
      "enteredWorkspace": "Just entered the workspace"
    },
    "greeting": {
      "afternoon": "Good afternoon",
      "evening": "Good evening",
      "morning": "Good morning"
    },
    "hero": {
      "description": "The knowledge workspace is ready for the next step.",
      "enterAiChat": "Open AI chat",
      "refresh": "Refresh home",
      "titleWithUser": "{{greeting}}, {{username}}.",
      "titleWithoutUser": "{{greeting}}.",
      "viewDocuments": "View documents"
    },
    "knowledgeBases": {
      "button": "Keep building",
      "defaultDescription": "No description yet. Consider explaining what this knowledge base is meant to solve.",
      "empty": "No knowledge base yet. Create a topic container first.",
      "eyebrow": "Knowledge base list",
      "title": "Current content structure"
    },
    "progress": {
      "conversation": {
        "done": "You already have {{count}} conversations",
        "title": "Start asking questions",
        "todo": "Start your first conversation so the documents move into real usage."
      },
      "document": {
        "done": "You already have {{count}} documents",
        "title": "Import documents",
        "todo": "Upload PDFs, Markdown files, or plain text so the knowledge base has searchable content."
      },
      "eyebrow": "Workflow progress",
      "knowledge": {
        "done": "You already have {{count}} knowledge bases",
        "title": "Create a knowledge base",
        "todo": "Create a topic entry first. Documents and conversations will build around it."
      }
    },
    "recentDocuments": {
      "button": "View all",
      "collectedAt": "Collected at {{time}}",
      "empty": "No documents yet. Upload one to get started.",
      "eyebrow": "Recent documents",
      "title": "Recently imported knowledge"
    },
    "recentSessions": {
      "button": "Open chat",
      "empty": "No Q&A records yet. Start your first conversation.",
      "eyebrow": "Recent conversations",
      "generalConversation": "General conversation",
      "knowledgeConversation": "Knowledge conversation",
      "title": "AI conversation timeline"
    },
    "sourceType": {
      "editor": "Editor document",
      "upload": "Uploaded document"
    },
    "stats": {
      "conversation": {
        "caption": "Includes both general chats and knowledge-base-linked conversations.",
        "label": "AI conversations"
      },
      "document": {
        "caption": "The home page shows the latest 6. Manage the rest on the documents page.",
        "label": "Documents"
      },
      "knowledge": {
        "caption": "Used to organize topics, documents, and Q&A scope.",
        "label": "Knowledge bases"
      },
      "readiness": {
        "caption": "Completed {{completed}} / 3 key setup steps.",
        "label": "Workspace progress"
      }
    },
    "summary": {
      "full": "The workspace is fully set up. You can keep expanding the knowledge base or jump back into AI chat for deeper questions.",
      "none": "Start with the three essentials: knowledge bases, documents, and conversations to get the workspace moving.",
      "one": "The foundation is ready. Add documents or conversations next to make the home page more useful.",
      "two": "Only one step remains before the full workflow is complete. This is a good time to start building conversation history."
    }
  },
  "knowledge": {
    "detail": {
      "deleteConfirm": "Are you sure you want to delete this document?",
      "description": "Description",
      "empty": "No documents yet",
      "fileSize": "File size",
      "fileSource": "File source",
      "indexStatus": "Index status",
      "loadedAll": "All documents have been loaded"
    },
    "sidebar": {
      "delete": {
        "content": "Are you sure you want to delete this knowledge base?",
        "title": "Delete knowledge base"
      },
      "form": {
        "description": {
          "label": "Description",
          "max": "Description must be no longer than 500 characters"
        },
        "name": {
          "label": "Name",
          "range": "Name is required and must be no longer than 100 characters"
        }
      },
      "menu": {
        "delete": "Delete",
        "edit": "Edit"
      },
      "modal": {
        "createTitle": "Create knowledge base",
        "editTitle": "Edit knowledge base"
      },
      "sectionTitle": "Knowledge bases"
    },
    "sourceType": {
      "editor": "Editor",
      "upload": "Upload"
    }
  },
  "layout": {
    "nav": {
      "aiChat": "AI Chat",
      "aiWrite": "AI Writing",
      "documents": "Documents"
    },
    "userMenu": {
      "logout": "Log out"
    }
  },
  "request": {
    "errors": {
      "authRequired": "Unauthorized. Please log in again",
      "refreshFailed": "Failed to refresh login session",
      "requestFailed": "Request failed",
      "requestSendFailed": "Failed to send request"
    },
    "notifications": {
      "requestFailedTitle": "Request failed"
    },
    "status": {
      "400": "Invalid request parameters",
      "401": "Unauthorized. Please log in again",
      "403": "Access denied",
      "404": "Requested resource was not found",
      "408": "Request timed out",
      "500": "The server is unavailable. Please try again later",
      "501": "Service not implemented",
      "502": "Bad gateway",
      "503": "Service unavailable",
      "504": "Gateway timeout"
    }
  }
}

export default Resources;
